sonata_block:
    default_contexts: [cms]
    blocks:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title: '%title%'
    title_logo: '%logo%'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AdminBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
